---
- hosts: ubuntu
  become: yes

  tasks:
    - name: Remove Apache, Mysql, PHP, Nginx
      apt: 
        name: ['apache2', 'mysql-server', 'libapache2-mod-php', 'php-mysql', 'httpd', 'python3-pymysql', 'php']
        state: absent
